//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 12:14:04 AM CEST 
//


package com.namespacetest;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for examRegistration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="examRegistration"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="value" type="{http://namespacetest.com}markValue"/&gt;
 *         &lt;element name="examName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="candidateName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="registrationDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "examRegistration", propOrder = {
    "value",
    "examName",
    "candidateName",
    "registrationDate"
})
public class ExamRegistration {

    @XmlSchemaType(name = "integer")
    protected int value;
    @XmlElement(required = true)
    protected String examName;
    @XmlElement(required = true)
    protected String candidateName;
    @XmlElement(required = true)
    protected String registrationDate;

    /**
     * Gets the value of the value property.
     * 
     */
    public int getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(int value) {
        this.value = value;
    }

    /**
     * Gets the value of the examName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExamName() {
        return examName;
    }

    /**
     * Sets the value of the examName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExamName(String value) {
        this.examName = value;
    }

    /**
     * Gets the value of the candidateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCandidateName() {
        return candidateName;
    }

    /**
     * Sets the value of the candidateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCandidateName(String value) {
        this.candidateName = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationDate(String value) {
        this.registrationDate = value;
    }

}
