//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 12:14:04 AM CEST 
//


package com.namespacetest;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="responseResult" type="{http://namespacetest.com}examRegistration"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseResult"
})
@XmlRootElement(name = "getExamResponse")
public class GetExamResponse {

    @XmlElement(required = true)
    protected ExamRegistration responseResult;

    /**
     * Gets the value of the responseResult property.
     * 
     * @return
     *     possible object is
     *     {@link ExamRegistration }
     *     
     */
    public ExamRegistration getResponseResult() {
        return responseResult;
    }

    /**
     * Sets the value of the responseResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExamRegistration }
     *     
     */
    public void setResponseResult(ExamRegistration value) {
        this.responseResult = value;
    }

}
